name: 'Common Setup'
description: 'Sets up the environment for building the project'

inputs:
  ssh-private-key:
    description: 'SSH private key for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Pull Git LFS resources
      shell: bash
      run: |
        git lfs install 
        git lfs pull

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.12.1

    - name: Check conan cache
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: |
          ~/.conan2
          ~/.conan
        key: ${{ runner.os }}-conan-cache

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@main
      with:
        vulkan-query-version: 1.3.268.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true